/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shiming_imageloader_jni_JniUtils */

#ifndef _Included_com_shiming_imageloader_jnitest_JniUtils
#define _Included_com_shiming_imageloader_jnitest_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Java_com_shiming_imageloader_jnitest_JniUtils
 * Method:    blurIntArray
 * Signature: ([IIII)V
 * 可千万要加上 Java_的前缀 ，要不然找不到啊
 */

JNIEXPORT void JNICALL Java_com_shiming_imageloader_jnitest_JniUtils_blurIntArray
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
